# Generated from data/bus_data.json — baseline timetable used until the weekly scraper stores a newer one.
# Regenerate with scripts/build_assets_data.py
BUS_DATA: dict = {'title': '2025年度 基準時刻表',
 'notes': {'◎': '经永山站到达学校的班次',
           '*': '经永山站到达圣迹樱丘站的班次',
           'M': '大学生专用微型巴士（仅周一～周四）',
           'C': '中学生专用班次',
           'K': '高中生专用班次'},
 'weekday': {'fromSeisekiToSchool': [{'hour': 7,
                                      'times': [{'hour': 7,
                                                 'minute': 25,
                                                 'isSpecial': True,
                                                 'specialNote': 'C'}]},
                                     {'hour': 8,
                                      'times': [{'hour': 8,
                                                 'minute': 0,
                                                 'isSpecial': True,
                                                 'specialNote': 'K'},
                                                {'hour': 8,
                                                 'minute': 35,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 10,
                                      'times': [{'hour': 10,
                                                 'minute': 15,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 11,
                                      'times': [{'hour': 11,
                                                 'minute': 0,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 12,
                                      'times': [{'hour': 12,
                                                 'minute': 40,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 13,
                                      'times': [{'hour': 13,
                                                 'minute': 25,
                                                 'isSpecial': True,
                                                 'specialNote': '◎'}]},
                                     {'hour': 14,
                                      'times': [{'hour': 14,
                                                 'minute': 10,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 15,
                                      'times': [{'hour': 15,
                                                 'minute': 10,
                                                 'isSpecial': False,
                                                 'specialNote': None}]}],
             'fromNagayamaToSchool': [{'hour': 7,
                                       'times': [{'hour': 7,
                                                  'minute': 10,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 7,
                                                  'minute': 15,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 7,
                                                  'minute': 25,
                                                  'isSpecial': True,
                                                  'specialNote': 'C'},
                                                 {'hour': 7,
                                                  'minute': 35,
                                                  'isSpecial': True,
                                                  'specialNote': 'C'},
                                                 {'hour': 7,
                                                  'minute': 40,
                                                  'isSpecial': True,
                                                  'specialNote': 'C'},
                                                 {'hour': 7,
                                                  'minute': 50,
                                                  'isSpecial': True,
                                                  'specialNote': 'K'}]},
                                      {'hour': 8,
                                       'times': [{'hour': 8,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': 'K'},
                                                 {'hour': 8,
                                                  'minute': 5,
                                                  'isSpecial': True,
                                                  'specialNote': 'K'},
                                                 {'hour': 8,
                                                  'minute': 20,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 8,
                                                  'minute': 35,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 8,
                                                  'minute': 40,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 8,
                                                  'minute': 45,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 10,
                                       'times': [{'hour': 10,
                                                  'minute': 0,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 10,
                                                  'minute': 15,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 10,
                                                  'minute': 20,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 10,
                                                  'minute': 25,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 10,
                                                  'minute': 55,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 11,
                                       'times': [{'hour': 11,
                                                  'minute': 45,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 12,
                                       'times': [{'hour': 12,
                                                  'minute': 15,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 12,
                                                  'minute': 35,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 12,
                                                  'minute': 45,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 13,
                                       'times': [{'hour': 13,
                                                  'minute': 40,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 14,
                                       'times': [{'hour': 14,
                                                  'minute': 15,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 14,
                                                  'minute': 55,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 16,
                                       'times': [{'hour': 16,
                                                  'minute': 0,
                                                  'isSpecial': False,
                                                  'specialNote': None}]}],
             'fromSchoolToNagayama': [{'hour': 9,
                                       'times': [{'hour': 9,
                                                  'minute': 45,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 10,
                                       'times': [{'hour': 10,
                                                  'minute': 5,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 10,
                                                  'minute': 40,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 11,
                                       'times': [{'hour': 11,
                                                  'minute': 30,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 12,
                                       'times': [{'hour': 12,
                                                  'minute': 0,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 12,
                                                  'minute': 20,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 12,
                                                  'minute': 30,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 13,
                                       'times': [{'hour': 13,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': '*',
                                                  'derivedFrom': 'seiseki'}]},
                                      {'hour': 14,
                                       'times': [{'hour': 14,
                                                  'minute': 0,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 14,
                                                  'minute': 40,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 14,
                                                  'minute': 45,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 15,
                                       'times': [{'hour': 15,
                                                  'minute': 15,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 15,
                                                  'minute': 45,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 16,
                                       'times': [{'hour': 16,
                                                  'minute': 0,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 16,
                                                  'minute': 5,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 16,
                                                  'minute': 15,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 16,
                                                  'minute': 30,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 16,
                                                  'minute': 45,
                                                  'isSpecial': True,
                                                  'specialNote': '*',
                                                  'derivedFrom': 'seiseki'}]},
                                      {'hour': 17,
                                       'times': [{'hour': 17,
                                                  'minute': 15,
                                                  'isSpecial': True,
                                                  'specialNote': '*',
                                                  'derivedFrom': 'seiseki'},
                                                 {'hour': 17,
                                                  'minute': 45,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 17,
                                                  'minute': 50,
                                                  'isSpecial': True,
                                                  'specialNote': '*',
                                                  'derivedFrom': 'seiseki'}]},
                                      {'hour': 18,
                                       'times': [{'hour': 18,
                                                  'minute': 0,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 18,
                                                  'minute': 5,
                                                  'isSpecial': True,
                                                  'specialNote': '*',
                                                  'derivedFrom': 'seiseki'},
                                                 {'hour': 18,
                                                  'minute': 35,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 18,
                                                  'minute': 40,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 19,
                                       'times': [{'hour': 19,
                                                  'minute': 40,
                                                  'isSpecial': True,
                                                  'specialNote': '*',
                                                  'derivedFrom': 'seiseki'}]}],
             'fromSchoolToSeiseki': [{'hour': 9,
                                      'times': [{'hour': 9,
                                                 'minute': 55,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 10,
                                      'times': [{'hour': 10,
                                                 'minute': 40,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 12,
                                      'times': [{'hour': 12,
                                                 'minute': 20,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 13,
                                      'times': [{'hour': 13,
                                                 'minute': 0,
                                                 'isSpecial': True,
                                                 'specialNote': '*'},
                                                {'hour': 13,
                                                 'minute': 50,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 14,
                                      'times': [{'hour': 14,
                                                 'minute': 50,
                                                 'isSpecial': False,
                                                 'specialNote': None}]},
                                     {'hour': 16,
                                      'times': [{'hour': 16,
                                                 'minute': 5,
                                                 'isSpecial': False,
                                                 'specialNote': None},
                                                {'hour': 16,
                                                 'minute': 25,
                                                 'isSpecial': False,
                                                 'specialNote': None},
                                                {'hour': 16,
                                                 'minute': 45,
                                                 'isSpecial': True,
                                                 'specialNote': '*'}]},
                                     {'hour': 17,
                                      'times': [{'hour': 17,
                                                 'minute': 15,
                                                 'isSpecial': True,
                                                 'specialNote': '*'},
                                                {'hour': 17,
                                                 'minute': 50,
                                                 'isSpecial': True,
                                                 'specialNote': '*'}]},
                                     {'hour': 18,
                                      'times': [{'hour': 18,
                                                 'minute': 5,
                                                 'isSpecial': True,
                                                 'specialNote': '*'},
                                                {'hour': 18,
                                                 'minute': 40,
                                                 'isSpecial': True,
                                                 'specialNote': '*'}]},
                                     {'hour': 19,
                                      'times': [{'hour': 19,
                                                 'minute': 40,
                                                 'isSpecial': True,
                                                 'specialNote': '*'}]}]},
 'saturday': {'fromSeisekiToSchool': [{'hour': 7,
                                       'times': [{'hour': 7,
                                                  'minute': 25,
                                                  'isSpecial': True,
                                                  'specialNote': 'C'}]},
                                      {'hour': 8,
                                       'times': [{'hour': 8,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': 'K'},
                                                 {'hour': 8,
                                                  'minute': 25,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'},
                                                 {'hour': 8,
                                                  'minute': 55,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'}]},
                                      {'hour': 9,
                                       'times': [{'hour': 9,
                                                  'minute': 25,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'},
                                                 {'hour': 9,
                                                  'minute': 55,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'}]},
                                      {'hour': 10,
                                       'times': [{'hour': 10,
                                                  'minute': 25,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'},
                                                 {'hour': 10,
                                                  'minute': 55,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'}]},
                                      {'hour': 11,
                                       'times': [{'hour': 11,
                                                  'minute': 55,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'}]},
                                      {'hour': 12,
                                       'times': [{'hour': 12,
                                                  'minute': 50,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'}]},
                                      {'hour': 13,
                                       'times': [{'hour': 13,
                                                  'minute': 20,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'}]},
                                      {'hour': 14,
                                       'times': [{'hour': 14,
                                                  'minute': 25,
                                                  'isSpecial': True,
                                                  'specialNote': '◎'}]}],
              'fromNagayamaToSchool': [{'hour': 7,
                                        'times': [{'hour': 7,
                                                   'minute': 10,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 7,
                                                   'minute': 15,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 7,
                                                   'minute': 25,
                                                   'isSpecial': True,
                                                   'specialNote': 'C'},
                                                  {'hour': 7,
                                                   'minute': 35,
                                                   'isSpecial': True,
                                                   'specialNote': 'C'},
                                                  {'hour': 7,
                                                   'minute': 40,
                                                   'isSpecial': True,
                                                   'specialNote': 'C'},
                                                  {'hour': 7,
                                                   'minute': 50,
                                                   'isSpecial': True,
                                                   'specialNote': 'K'}]},
                                       {'hour': 8,
                                        'times': [{'hour': 8,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': 'K'},
                                                  {'hour': 8,
                                                   'minute': 5,
                                                   'isSpecial': True,
                                                   'specialNote': 'K'},
                                                  {'hour': 8,
                                                   'minute': 40,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 9,
                                        'times': [{'hour': 9,
                                                   'minute': 10,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 9,
                                                   'minute': 40,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 10,
                                        'times': [{'hour': 10,
                                                   'minute': 10,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 10,
                                                   'minute': 40,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 11,
                                        'times': [{'hour': 11,
                                                   'minute': 10,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 12,
                                        'times': [{'hour': 12,
                                                   'minute': 10,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 12,
                                                   'minute': 45,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 12,
                                                   'minute': 50,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 13,
                                        'times': [{'hour': 13,
                                                   'minute': 5,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 13,
                                                   'minute': 35,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 14,
                                        'times': [{'hour': 14,
                                                   'minute': 40,
                                                   'isSpecial': False,
                                                   'specialNote': None}]}],
              'fromSchoolToNagayama': [{'hour': 9,
                                        'times': [{'hour': 9,
                                                   'minute': 30,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]},
                                       {'hour': 10,
                                        'times': [{'hour': 10,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'},
                                                  {'hour': 10,
                                                   'minute': 30,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]},
                                       {'hour': 11,
                                        'times': [{'hour': 11,
                                                   'minute': 0,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 11,
                                                   'minute': 30,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 11,
                                                   'minute': 35,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 11,
                                                   'minute': 40,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 11,
                                                   'minute': 55,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 12,
                                        'times': [{'hour': 12,
                                                   'minute': 25,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 12,
                                                   'minute': 30,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 12,
                                                   'minute': 35,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 12,
                                                   'minute': 50,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 12,
                                                   'minute': 55,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]},
                                       {'hour': 13,
                                        'times': [{'hour': 13,
                                                   'minute': 25,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]},
                                       {'hour': 14,
                                        'times': [{'hour': 14,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'},
                                                  {'hour': 14,
                                                   'minute': 30,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]},
                                       {'hour': 15,
                                        'times': [{'hour': 15,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'},
                                                  {'hour': 15,
                                                   'minute': 30,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]},
                                       {'hour': 16,
                                        'times': [{'hour': 16,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'},
                                                  {'hour': 16,
                                                   'minute': 30,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'},
                                                  {'hour': 16,
                                                   'minute': 45,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 17,
                                        'times': [{'hour': 17,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'},
                                                  {'hour': 17,
                                                   'minute': 30,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]},
                                       {'hour': 18,
                                        'times': [{'hour': 18,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'},
                                                  {'hour': 18,
                                                   'minute': 40,
                                                   'isSpecial': True,
                                                   'specialNote': '*',
                                                   'derivedFrom': 'seiseki'}]}],
              'fromSchoolToSeiseki': [{'hour': 9,
                                       'times': [{'hour': 9,
                                                  'minute': 30,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 10,
                                       'times': [{'hour': 10,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': '*'},
                                                 {'hour': 10,
                                                  'minute': 30,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 11,
                                       'times': [{'hour': 11,
                                                  'minute': 40,
                                                  'isSpecial': False,
                                                  'specialNote': None}]},
                                      {'hour': 12,
                                       'times': [{'hour': 12,
                                                  'minute': 30,
                                                  'isSpecial': False,
                                                  'specialNote': None},
                                                 {'hour': 12,
                                                  'minute': 55,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 13,
                                       'times': [{'hour': 13,
                                                  'minute': 25,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 14,
                                       'times': [{'hour': 14,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': '*'},
                                                 {'hour': 14,
                                                  'minute': 30,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 15,
                                       'times': [{'hour': 15,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': '*'},
                                                 {'hour': 15,
                                                  'minute': 30,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 16,
                                       'times': [{'hour': 16,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': '*'},
                                                 {'hour': 16,
                                                  'minute': 30,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 17,
                                       'times': [{'hour': 17,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': '*'},
                                                 {'hour': 17,
                                                  'minute': 30,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]},
                                      {'hour': 18,
                                       'times': [{'hour': 18,
                                                  'minute': 0,
                                                  'isSpecial': True,
                                                  'specialNote': '*'},
                                                 {'hour': 18,
                                                  'minute': 40,
                                                  'isSpecial': True,
                                                  'specialNote': '*'}]}]},
 'wednesday': {'fromSeisekiToSchool': [{'hour': 7,
                                        'times': [{'hour': 7,
                                                   'minute': 25,
                                                   'isSpecial': True,
                                                   'specialNote': 'C'}]},
                                       {'hour': 8,
                                        'times': [{'hour': 8,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': 'K'},
                                                  {'hour': 8,
                                                   'minute': 35,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 10,
                                        'times': [{'hour': 10,
                                                   'minute': 15,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 11,
                                        'times': [{'hour': 11,
                                                   'minute': 0,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 12,
                                        'times': [{'hour': 12,
                                                   'minute': 40,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 13,
                                        'times': [{'hour': 13,
                                                   'minute': 25,
                                                   'isSpecial': True,
                                                   'specialNote': '◎'}]},
                                       {'hour': 14,
                                        'times': [{'hour': 14,
                                                   'minute': 10,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 15,
                                        'times': [{'hour': 15,
                                                   'minute': 10,
                                                   'isSpecial': False,
                                                   'specialNote': None}]}],
               'fromNagayamaToSchool': [{'hour': 7,
                                         'times': [{'hour': 7,
                                                    'minute': 10,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 7,
                                                    'minute': 15,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 7,
                                                    'minute': 25,
                                                    'isSpecial': True,
                                                    'specialNote': 'C'},
                                                   {'hour': 7,
                                                    'minute': 35,
                                                    'isSpecial': True,
                                                    'specialNote': 'C'},
                                                   {'hour': 7,
                                                    'minute': 40,
                                                    'isSpecial': True,
                                                    'specialNote': 'C'},
                                                   {'hour': 7,
                                                    'minute': 50,
                                                    'isSpecial': True,
                                                    'specialNote': 'K'}]},
                                        {'hour': 8,
                                         'times': [{'hour': 8,
                                                    'minute': 0,
                                                    'isSpecial': True,
                                                    'specialNote': 'K'},
                                                   {'hour': 8,
                                                    'minute': 5,
                                                    'isSpecial': True,
                                                    'specialNote': 'K'},
                                                   {'hour': 8,
                                                    'minute': 20,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 8,
                                                    'minute': 35,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 8,
                                                    'minute': 40,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 8,
                                                    'minute': 45,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 10,
                                         'times': [{'hour': 10,
                                                    'minute': 0,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 10,
                                                    'minute': 15,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 10,
                                                    'minute': 20,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 10,
                                                    'minute': 25,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 10,
                                                    'minute': 55,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 11,
                                         'times': [{'hour': 11,
                                                    'minute': 45,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 12,
                                         'times': [{'hour': 12,
                                                    'minute': 15,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 12,
                                                    'minute': 35,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 12,
                                                    'minute': 45,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 13,
                                         'times': [{'hour': 13,
                                                    'minute': 40,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 14,
                                         'times': [{'hour': 14,
                                                    'minute': 15,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 14,
                                                    'minute': 55,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 16,
                                         'times': [{'hour': 16,
                                                    'minute': 0,
                                                    'isSpecial': False,
                                                    'specialNote': None}]}],
               'fromSchoolToNagayama': [{'hour': 9,
                                         'times': [{'hour': 9,
                                                    'minute': 45,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 10,
                                         'times': [{'hour': 10,
                                                    'minute': 5,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 10,
                                                    'minute': 40,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 11,
                                         'times': [{'hour': 11,
                                                    'minute': 30,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 12,
                                         'times': [{'hour': 12,
                                                    'minute': 0,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 12,
                                                    'minute': 20,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 12,
                                                    'minute': 30,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 12,
                                                    'minute': 55,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 13,
                                         'times': [{'hour': 13,
                                                    'minute': 0,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 13,
                                                    'minute': 5,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 13,
                                                    'minute': 20,
                                                    'isSpecial': True,
                                                    'specialNote': '*',
                                                    'derivedFrom': 'seiseki'}]},
                                        {'hour': 14,
                                         'times': [{'hour': 14,
                                                    'minute': 0,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 14,
                                                    'minute': 35,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 14,
                                                    'minute': 40,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 14,
                                                    'minute': 50,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 15,
                                         'times': [{'hour': 15,
                                                    'minute': 0,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 15,
                                                    'minute': 15,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 15,
                                                    'minute': 45,
                                                    'isSpecial': False,
                                                    'specialNote': None}]},
                                        {'hour': 16,
                                         'times': [{'hour': 16,
                                                    'minute': 5,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 16,
                                                    'minute': 15,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 16,
                                                    'minute': 30,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 16,
                                                    'minute': 45,
                                                    'isSpecial': True,
                                                    'specialNote': '*',
                                                    'derivedFrom': 'seiseki'}]},
                                        {'hour': 17,
                                         'times': [{'hour': 17,
                                                    'minute': 15,
                                                    'isSpecial': True,
                                                    'specialNote': '*',
                                                    'derivedFrom': 'seiseki'},
                                                   {'hour': 17,
                                                    'minute': 50,
                                                    'isSpecial': True,
                                                    'specialNote': '*',
                                                    'derivedFrom': 'seiseki'}]},
                                        {'hour': 18,
                                         'times': [{'hour': 18,
                                                    'minute': 0,
                                                    'isSpecial': False,
                                                    'specialNote': None},
                                                   {'hour': 18,
                                                    'minute': 5,
                                                    'isSpecial': True,
                                                    'specialNote': '*',
                                                    'derivedFrom': 'seiseki'},
                                                   {'hour': 18,
                                                    'minute': 40,
                                                    'isSpecial': True,
                                                    'specialNote': '*',
                                                    'derivedFrom': 'seiseki'}]},
                                        {'hour': 19,
                                         'times': [{'hour': 19,
                                                    'minute': 40,
                                                    'isSpecial': True,
                                                    'specialNote': '*',
                                                    'derivedFrom': 'seiseki'}]}],
               'fromSchoolToSeiseki': [{'hour': 9,
                                        'times': [{'hour': 9,
                                                   'minute': 55,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 10,
                                        'times': [{'hour': 10,
                                                   'minute': 40,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 12,
                                        'times': [{'hour': 12,
                                                   'minute': 20,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 13,
                                        'times': [{'hour': 13,
                                                   'minute': 0,
                                                   'isSpecial': True,
                                                   'specialNote': '*'},
                                                  {'hour': 13,
                                                   'minute': 20,
                                                   'isSpecial': True,
                                                   'specialNote': '*'},
                                                  {'hour': 13,
                                                   'minute': 50,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 14,
                                        'times': [{'hour': 14,
                                                   'minute': 50,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 15,
                                        'times': [{'hour': 15,
                                                   'minute': 25,
                                                   'isSpecial': False,
                                                   'specialNote': None}]},
                                       {'hour': 16,
                                        'times': [{'hour': 16,
                                                   'minute': 5,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 16,
                                                   'minute': 25,
                                                   'isSpecial': False,
                                                   'specialNote': None},
                                                  {'hour': 16,
                                                   'minute': 45,
                                                   'isSpecial': True,
                                                   'specialNote': '*'}]},
                                       {'hour': 17,
                                        'times': [{'hour': 17,
                                                   'minute': 15,
                                                   'isSpecial': True,
                                                   'specialNote': '*'},
                                                  {'hour': 17,
                                                   'minute': 50,
                                                   'isSpecial': True,
                                                   'specialNote': '*'}]},
                                       {'hour': 18,
                                        'times': [{'hour': 18,
                                                   'minute': 5,
                                                   'isSpecial': True,
                                                   'specialNote': '*'},
                                                  {'hour': 18,
                                                   'minute': 40,
                                                   'isSpecial': True,
                                                   'specialNote': '*'}]},
                                       {'hour': 19,
                                        'times': [{'hour': 19,
                                                   'minute': 40,
                                                   'isSpecial': True,
                                                   'specialNote': '*'}]}]}}
