# Generated from data/teachers.json — regenerate with scripts/build_assets_data.py
TEACHERS: list[dict] = [{'name': '石川 晴子', 'furigana': 'いしかわ はるこ', 'email': 'ishikawa-h@tama.ac.jp'},
 {'name': '出原 至道', 'furigana': 'いではら のりみち', 'email': 'idehara@tama.ac.jp'},
 {'name': '今泉 忠', 'furigana': 'いまいずみ ただし', 'email': 'imaizumi@tama.ac.jp'},
 {'name': '梅澤 佳子', 'furigana': 'うめざわ よしこ', 'email': 'umezawa@tama.ac.jp'},
 {'name': '落合 孝彦', 'furigana': 'おちあい たかひこ', 'email': 'ochiai-t@tama.ac.jp'},
 {'name': '加藤 みずき', 'furigana': 'かとう みずき', 'email': 'kato-mi@tama.ac.jp'},
 {'name': '金 美徳', 'furigana': 'きむ みとく', 'email': 'kim-m@tama.ac.jp'},
 {'name': '木村 太一', 'furigana': 'きむら たいち', 'email': 'kimura-ta@tama.ac.jp'},
 {'name': '久保田 貴文', 'furigana': 'くぼた たかふみ', 'email': 'kubota@tama.ac.jp'},
 {'name': '小西 英行', 'furigana': 'こにし ひでゆき', 'email': 'konishi-h@tama.ac.jp'},
 {'name': '小林 昭菜', 'furigana': 'こばやし あきな', 'email': 'kobayashi-a@tama.ac.jp'},
 {'name': '小林 英夫', 'furigana': 'こばやし ひでお', 'email': 'kobayashi-h@tama.ac.jp'},
 {'name': '彩藤 ひろみ', 'furigana': 'さいとう ひろみ', 'email': 'hiro@tama.ac.jp'},
 {'name': '齋藤S. 裕美', 'furigana': 'さいとうえす ひろみ', 'email': 'saitouh@tama.ac.jp'},
 {'name': '下井 直毅', 'furigana': 'しもい なおき', 'email': 'shimoi@tama.ac.jp'},
 {'name': '新西 誠人', 'furigana': 'しんにし まこと', 'email': 'shinnishi-m@tama.ac.jp'},
 {'name': '菅沼 睦', 'furigana': 'すがぬま むつみ', 'email': 'suganuma-m@tama.ac.jp'},
 {'name': '杉田 文章', 'furigana': 'すぎた ふみあき', 'email': 'sugita@tama.ac.jp'},
 {'name': '高橋 恭寛', 'furigana': 'たかはし やすひろ', 'email': 'takahashi-ya@tama.ac.jp'},
 {'name': '田中 友理', 'furigana': 'たなか ゆり', 'email': 'tanaka-yu@tama.ac.jp'},
 {'name': '千ヶ崎 清孝', 'furigana': 'ちがさき きよたか', 'email': 'chigasaki-k@tama.ac.jp'},
 {'name': '趙 佑鎭', 'furigana': 'ちょう うじん', 'email': 'cho@tama.ac.jp'},
 {'name': '内藤 旭惠', 'furigana': 'ないとう あきえ', 'email': 'naito-a@tama.ac.jp'},
 {'name': '中澤 弥', 'furigana': 'なかざわ わたる', 'email': 'nakazawa@tama.ac.jp'},
 {'name': '中庭 光彦', 'furigana': 'なかにわ みつひこ', 'email': 'nakaniwa@tama.ac.jp'},
 {'name': '中村 その子', 'furigana': 'なかむら そのこ', 'email': 'sonoko-n@tama.ac.jp'},
 {'name': '中村 有一', 'furigana': 'なかむら ゆういち', 'email': 'naka@tama.ac.jp'},
 {'name': '長島 剛', 'furigana': 'ながしま つよし', 'email': 'nagashima-t@tama.ac.jp'},
 {'name': '野坂 美穂', 'furigana': 'のさか みほ', 'email': 'nosaka-m@tama.ac.jp'},
 {'name': '初見 康行', 'furigana': 'はつみ やすゆき', 'email': 'hatsumi@tama.ac.jp'},
 {'name': '巴特尓', 'furigana': 'ばーとる', 'email': 'baatar@tama.ac.jp'},
 {'name': '浜田 正幸', 'furigana': 'はまだ まさゆき', 'email': 'hamada-m@tama.ac.jp'},
 {'name': '樋笠 尭士', 'furigana': 'ひかさ たかし', 'email': 'hikasa@tama.ac.jp'},
 {'name': '増田 浩通', 'furigana': 'ますだ ひろゆき', 'email': 'masuda@tama.ac.jp'},
 {'name': '松本 祐一', 'furigana': 'まつもと ゆういち', 'email': 'matsumoto@tama.ac.jp'},
 {'name': '水盛 涼一', 'furigana': 'みずもり りょういち', 'email': 'mizumori-r@tama.ac.jp'},
 {'name': '良峯 徳和', 'furigana': 'よしみね のりかず', 'email': 'yoshimine@tama.ac.jp'},
 {'name': '青木 克彦', 'furigana': None, 'email': 'aoki-k@tama.ac.jp'},
 {'name': '赤澤 祐美', 'furigana': None, 'email': 'akasawa-y@tama.ac.jp'},
 {'name': '安 ウンビョル', 'furigana': None, 'email': 'ahn-e@tama.ac.jp'},
 {'name': '井出 晃憲', 'furigana': None, 'email': 'ide-a@tama.ac.jp'},
 {'name': '大森 拓哉', 'furigana': None, 'email': 'ohmori@tama.ac.jp'},
 {'name': '大森 良平', 'furigana': None, 'email': 'omori-r@tama.ac.jp'},
 {'name': '荻野 博司', 'furigana': None, 'email': 'ogino@tama.ac.jp'},
 {'name': '河合 敦', 'furigana': None, 'email': 'kawai-a@tama.ac.jp'},
 {'name': '高 昌弘', 'furigana': None, 'email': 'ko-c@tama.ac.jp'},
 {'name': '後藤 涼子', 'furigana': None, 'email': 'goto-r@tama.ac.jp'},
 {'name': '佐野 あゆみ', 'furigana': None, 'email': 'sano-a@tama.ac.jp'},
 {'name': '杉森 知也', 'furigana': None, 'email': 'sugimori@tama.ac.jp'},
 {'name': '関 秀雄', 'furigana': None, 'email': 'seki-h@tama.ac.jp'},
 {'name': '田 園', 'furigana': None, 'email': 'tian@tama.ac.jp'},
 {'name': '富山 篤', 'furigana': None, 'email': 'tomiyama-a@tama.ac.jp'},
 {'name': '中塚 義実', 'furigana': None, 'email': 'nakatsuka-y@tama.ac.jp'},
 {'name': '中湊 晃', 'furigana': None, 'email': 'nakaminato-a@tama.ac.jp'},
 {'name': '西住 祐亮', 'furigana': None, 'email': 'nishizumi-y@tama.ac.jp'},
 {'name': '羽田 昭裕', 'furigana': None, 'email': 'hada-a@tama.ac.jp'},
 {'name': '樋口 裕一', 'furigana': None, 'email': 'higuchi@tama.ac.jp'},
 {'name': '福角 有紘', 'furigana': None, 'email': 'fukuzumi@tama.ac.jp'},
 {'name': '真壁 昭夫', 'furigana': None, 'email': 'makabe-a@tama.ac.jp'},
 {'name': '水上 晃実', 'furigana': None, 'email': 'mizukami-t@tama.ac.jp'},
 {'name': '峯岸 久枝', 'furigana': None, 'email': 'minegishi-h@tama.ac.jp'},
 {'name': '宮本 純至', 'furigana': None, 'email': 'miyamoto-j@tama.ac.jp'},
 {'name': '明珍 儀隆', 'furigana': None, 'email': 'myochin-y@tama.ac.jp'},
 {'name': '結城 隆', 'furigana': None, 'email': 'yuki-t@tama.ac.jp'},
 {'name': '荻澤 紀子', 'furigana': None, 'email': 'ogizawa-n@tama.ac.jp'},
 {'name': '合田 和子', 'furigana': None, 'email': 'goda-k@tama.ac.jp'},
 {'name': '田口 綾子', 'furigana': None, 'email': 'taguchi-smis@tama.ac.jp'},
 {'name': '田中 美穂', 'furigana': None, 'email': 'tanaka-m@tama.ac.jp'},
 {'name': '吉田 理恵', 'furigana': None, 'email': 'yoshida-r@tama.ac.jp'},
 {'name': '相馬 淳一', 'furigana': None, 'email': 'soma-j@tama.ac.jp'},
 {'name': 'TIJ東京日本語研修所', 'furigana': None, 'email': 'tij@tama.ac.jp'},
 {'name': '日本数学検定協会', 'furigana': None, 'email': 'su-gaku@tama.ac.jp'},
 {'name': '葛本 幸枝', 'furigana': None, 'email': 'kuzumoto-s@tama.ac.jp'},
 {'name': '西村 公児', 'furigana': None, 'email': 'nishimura-k@tama.ac.jp'},
 {'name': '高瀬 義幸', 'furigana': None, 'email': 'takase-y@tama.ac.jp'}]
